Repository ucsb-cs156-s24/proj-happycows-s24-4pm-8, pull requests merged in 2024-05, with the labels that each got.

#14 JM - Commit Tracking Infrastructure Setup: Dockerfile, SystemInfo, pom.xml - [Backend]
  Dockerfile
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/models/SystemInfo.java
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
  src/test/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImplTests.java
Labels: 5

#13 Cp UI refractor
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
Labels: 5, Fix Me - See CR

#16 JM - Commit Tracking Through the SystemInfo API
  pom.xml
  src/main/java/edu/ucsb/cs156/happiercows/services/SystemInfoServiceImpl.java
Labels: 5

#18 JM - Added Suspended field to User
  src/main/java/edu/ucsb/cs156/happiercows/entities/User.java
  src/main/resources/db/migration/changes/User_Suspended_Field.json
Labels: 5

#20 JM - Added API Endpoints and Tests for Suspending and Restoring Users
  src/main/java/edu/ucsb/cs156/happiercows/controllers/UsersController.java
  src/test/java/edu/ucsb/cs156/happiercows/controllers/UsersControllerTests.java
Labels: 10

#31 NM-Better Profits Table Display with Pagination
  frontend/src/fixtures/pagedProfitsFixtures.js
  frontend/src/main/components/Commons/PagedProfitsTable.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/tests/components/Commons/PagedProfitsTable.test.js
  frontend/src/tests/components/Commons/Profits.test.js
Labels: 10

#29 va - Created Admin Announcements page and tests
  frontend/src/App.js
  frontend/src/main/components/Commons/CommonsTable.js
  frontend/src/main/pages/AdminAnnouncementsPage.js
  frontend/src/tests/components/Commons/CommonsTable.test.js
  frontend/src/tests/pages/AdminAnnouncementsPage.test.js
Labels: 5

#32 rk- fixed BUG: Disallow ability to navigate to unjoined commons
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/components/Commons/CommonsOverview.test.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 10

#38 et,cp - Homepage and PlayPage UI Refactor
  frontend/src/assets/WoodenBoard.png
  frontend/src/fixtures/currentUserFixtures.js
  frontend/src/index.css
  frontend/src/main/components/Commons/CommonsCard.js
  frontend/src/main/components/Commons/CommonsList.js
  frontend/src/main/components/Commons/CommonsOverview.js
  frontend/src/main/components/Commons/CommonsPlay.js
  frontend/src/main/components/Commons/FarmStats.js
  frontend/src/main/components/Commons/ManageCows.js
  frontend/src/main/components/Commons/Profits.js
  frontend/src/main/pages/HomePage.css
  frontend/src/main/pages/HomePage.js
  frontend/src/tests/components/Commons/CommonsPlay.test.js
  frontend/src/tests/pages/HomePage.test.js
Labels: 10

#36 CP - FEATURE: Swagger option on navbar
  src/main/resources/application-development.properties
  src/main/resources/application-production.properties
Labels: 5

#39 rk - fixed BUG: Disallow ability to navigate to commons not created yet
  frontend/src/main/pages/PlayPage.js
  frontend/src/tests/pages/PlayPage.test.js
Labels: 5

#23 JM - Added Authorization Gatekeeping for Suspended Users and Automatic Role Interception
  src/main/java/edu/ucsb/cs156/happiercows/interceptors/RoleUserInterceptor.java
  src/main/java/edu/ucsb/cs156/happiercows/interceptors/RoleUserInterceptorAppConfig.java
  src/test/java/edu/ucsb/cs156/happiercows/interceptors/RoleUserInterceptorTests.java
Labels: s24-4pm-8

#25 JM - Added Incremental Pitest Support
  README.md
  pom.xml
Labels: 5, s24-4pm-8
